#!/bin/sh /etc/rc.common
START=99
USE_PROCD=1

start_service() {
    sleep 60
    echo "*/3 * * * * /usr/lib/superwifi/superwifi_quota_tracking.sh" >> /etc/crontabs/root
    /etc/init.d/cron restart
}

stop_service() {
    sed -i '/superwifi_quota_tracking.sh/d' /etc/crontabs/root
    /etc/init.d/cron restart
}
